### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by Rigaln** [ArvinZJC/PaimonTray#10]
如果你把它添加到crowdin，我将翻译它。

**Comment by ArvinZJC** [comment]
Providing the ways to contribute to the app's internationalisation ability is already in my plan. However, no updates on it for a bit long time due to some personal reasons. Anyway, Thanks for your advice, and I appreciate your patience.

**Comment by ArvinZJC** [comment]
> 如果你把它添加到crowdin，我将翻译它。

With the release of V1.1-stable.1, you are welcome to provide your translations in [Crowdin](https://crowdin.com/project/paimontray). Anyway, thanks much for your advice!
