### ISSUE TITLE
Display scale may destroy the main window's layout if it is not 100%

### ISSUE THREAD

**Issue by lingyired** [ArvinZJC/PaimonTray#11]
![UI bug](https://user-images.githubusercontent.com/804785/193199360-e507370f-87e6-4a24-b314-ab251f98a8c1.png)

如图所示，我不得不切回原缩放（100%）来添加账号。

**Comment by lingyired** [comment]
截图中当前的显示器缩放比例为 125% ，我测试了 150% 也是一样。

系统是 Win 10 21H1， 显示器是 2K 分辨率

**Comment by ArvinZJC** [comment]
dbq，这个最初就是兴趣开发，测试只在开发机 Win 11 最新版做过测试，刚开了下 Win 10 虚机，问题可以复现，且各分辨率下均有异常，这个还需要调研具体影响哪些版本，以及是否是 WindowsAppSdk 的问题，因为根据经验之前很多问题都是这个不太成熟的东西版本更新时会造成。
此外，Win 10 上似乎还有表情字体缺失导致的图标异常问题，感谢反馈。
最近比较忙，等抽空看看的。或者，欢迎 PR~

**Comment by PIut02** [comment]
在win11 22h2上使用2k缩放175也会有显示比例问题

**Comment by ArvinZJC** [comment]
- [ ] Sort out a solution.
- [ ] Fix the bug in a dev branch.
- [ ] Include the fix in a release.

**Comment by ArvinZJC** [comment]
As you can see, the main window cannot be resized manually. Its size is calculated as per the content on it. However, I forgot to consider the rasterisation scale in the calculation causing this serious issue. A solution has been developed, and the fix will be merged in the next release.
