### ISSUE TITLE
Icons may display as garbage characters on Windows 10

### ISSUE THREAD

**Issue by ArvinZJC** [ArvinZJC/PaimonTray#12]
![image](https://user-images.githubusercontent.com/41031053/200159000-04fee948-7649-4aeb-9a38-fb71e0bc52c8.png)

**Comment by PIut02** [comment]
是否尝试过安装[Segoe Fluent Icons](https://file.xunkong.cc/download/font/Segoe%20Fluent%20Icons.ttf)字体？这个字体win11上的所以win10设备需要自行安装

**Comment by ArvinZJC** [comment]
> 是否尝试过安装[Segoe Fluent Icons](https://file.xunkong.cc/download/font/Segoe%20Fluent%20Icons.ttf)字体？这个字体是win11上的所以win10设备需要自行安装

安装 Segoe Fluent Icons 暂不考虑作为首选解决办法，原因在于所使用的 WinUI 3 原生控件应能根据系统选择合适的字体。这个之前测试是没有问题的，无论 Win 10 还是 Win 11 都能正确显示配置的图标，感觉就是 Win10 哪个版本系统更新后才出现的问题，目前的思路是看下 Win10 上是不是错误地使用了 Win11 的字体，如果是的话，就是 Windows App SDK 的问题，那倒是比系统更新带来的问题好办的多 ~~（前提是我这个社畜有时间）~~ 。

`<FontIcon FontFamily="{StaticResource SymbolThemeFontFamily}" Glyph="&#xE700;"/>`

[Segoe MDL2 Assets icons](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-ui-symbol-font)
[Segoe Fluent Icons font](https://learn.microsoft.com/en-us/windows/apps/design/style/segoe-fluent-icons-font#pua-e700-e900)

**Comment by ArvinZJC** [comment]
I can now confirm that this issue is caused by the bug of Windows App SDK (maybe v1.0+). A workaround will be developed to fix this issue.
