### ISSUE TITLE
Display problems with different zoom ratios

### ISSUE THREAD

**Issue by stevened7246** [ArvinZJC/PaimonTray#14]
There will be problems with using 1920x1080 125% zoom display under windows11
![image](https://user-images.githubusercontent.com/97885306/201119097-c7f9880a-5cb4-4357-bece-f813f8e60573.png)

**Comment by stevened7246** [comment]
刚刚发现有重复的issues，抱歉~~

**Comment by ArvinZJC** [comment]
Thx, duplicate of #11
