### ISSUE TITLE
Customise the main window's position

### ISSUE THREAD

**Issue by stevened7246** [ArvinZJC/PaimonTray#31]
开启自动隐藏工具列后会被挡到
![image](https://user-images.githubusercontent.com/97885306/210796408-8ceab4ec-e873-4c4f-8feb-969e6cdb56e6.png)
![image](https://user-images.githubusercontent.com/97885306/210796490-96ca71eb-1082-4b3f-849f-25f16b092a91.png)
关闭与美观都有一些问题

**Comment by ArvinZJC** [comment]
优化计划已包含：允许用户选择主窗口位置（左上角、左下角、右上角、右下角，如果可以的话根据任务栏位置自动选择）。因为 PaimonTray 的定位是任务栏应用/托盘应用，后续评估后可能考虑允许用户在上面基础上定义偏移量（或其他方案），允许通过键盘快捷键控制显示/隐藏主界面等功能。

请知：以上只能算是小优化，严格意义上不是 bug，故优先级较低。自动隐藏的任务栏会遮挡应用其实是正常的，最大化的应用也不会因为触发显示了隐藏的任务栏而调整窗口大小。**当前，在自动隐藏任务栏显示时，点击主界面可使主界面遮挡任务栏，点击任务栏可使任务栏遮挡主界面。隐藏主界面除了通过点击托盘图标，或右击托盘图标在菜单中选择，还可以在主界面导航栏的更多按钮触发菜单中选择。**
